//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyingSnow.Contract.Bill
{
    using System;
    using System.Collections.Generic;

    public partial class ParlayBill : Bill
    {
        public string GameTypeName1 { get; set; }
        public string GameTypeName2 { get; set; }
        public string GameTypeName3 { get; set; }
        public string GameTypeName4 { get; set; }
        public string GameTypeName5 { get; set; }
        public string GameTypeName6 { get; set; }
        public string GameTypeName7 { get; set; }
        public string GameTypeName8 { get; set; }
        public string GameTypeName9 { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string Content0 { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public string Content4 { get; set; }
        public string Content5 { get; set; }
        public string Content6 { get; set; }
        public string Content7 { get; set; }
        public string Content8 { get; set; }
        public string Content9 { get; set; }
        /// <summary>
        /// 下注队伍
        /// </summary>
        public string BetTeam0 { get; set; }
        public string BetTeam1 { get; set; }
        public string BetTeam2 { get; set; }
        public string BetTeam3 { get; set; }
        public string BetTeam4 { get; set; }
        public string BetTeam5 { get; set; }
        public string BetTeam6 { get; set; }
        public string BetTeam7 { get; set; }
        public string BetTeam8 { get; set; }
        public string BetTeam9 { get; set; }
        public Nullable<double> Odds0 { get; set; }
        public Nullable<double> Odds1 { get; set; }
        public Nullable<double> Odds2 { get; set; }
        public Nullable<double> Odds3 { get; set; }
        public Nullable<double> Odds4 { get; set; }
        public Nullable<double> Odds5 { get; set; }
        public Nullable<double> Odds6 { get; set; }
        public Nullable<double> Odds7 { get; set; }
        public Nullable<double> Odds8 { get; set; }
        public Nullable<double> Odds9 { get; set; }
        /// <summary>
        /// 让分
        /// </summary>
        public Nullable<double> Spread0_1 { get; set; }
        public Nullable<double> Spread0_2 { get; set; }
        public Nullable<double> Spread0_3 { get; set; }
        public Nullable<double> Spread0_4 { get; set; }
        public Nullable<double> Spread0_5 { get; set; }
        public Nullable<double> Spread0_6 { get; set; }
        public Nullable<double> Spread0_7 { get; set; }
        public Nullable<double> Spread0_8 { get; set; }
        public Nullable<double> Spread0_9 { get; set; }
        public Nullable<double> Spread0_10 { get; set; }
        public Nullable<int> Spread1_1 { get; set; }
        public Nullable<int> Spread1_2 { get; set; }
        public Nullable<int> Spread1_3 { get; set; }
        public Nullable<int> Spread1_4 { get; set; }
        public Nullable<int> Spread1_5 { get; set; }
        public Nullable<int> Spread1_6 { get; set; }
        public Nullable<int> Spread1_7 { get; set; }
        public Nullable<int> Spread1_8 { get; set; }
        public Nullable<int> Spread1_9 { get; set; }
        public Nullable<int> Spread1_10 { get; set; }
        public Nullable<double> Spread2_1 { get; set; }
        public Nullable<double> Spread2_2 { get; set; }
        public Nullable<double> Spread2_3 { get; set; }
        public Nullable<double> Spread2_4 { get; set; }
        public Nullable<double> Spread2_5 { get; set; }
        public Nullable<double> Spread2_6 { get; set; }
        public Nullable<double> Spread2_7 { get; set; }
        public Nullable<double> Spread2_8 { get; set; }
        public Nullable<double> Spread2_9 { get; set; }
        public Nullable<double> Spread2_10 { get; set; }
        public Nullable<int> Spread3_1 { get; set; }
        public Nullable<int> Spread3_2 { get; set; }
        public Nullable<int> Spread3_3 { get; set; }
        public Nullable<int> Spread3_4 { get; set; }
        public Nullable<int> Spread3_5 { get; set; }
        public Nullable<int> Spread3_6 { get; set; }
        public Nullable<int> Spread3_7 { get; set; }
        public Nullable<int> Spread3_8 { get; set; }
        public Nullable<int> Spread3_9 { get; set; }
        public Nullable<int> Spread3_10 { get; set; }
        /// <summary>
        /// 大小
        /// </summary>
        public Nullable<double> Score0_1 { get; set; }
        public Nullable<double> Score0_2 { get; set; }
        public Nullable<double> Score0_3 { get; set; }
        public Nullable<double> Score0_4 { get; set; }
        public Nullable<double> Score0_5 { get; set; }
        public Nullable<double> Score0_6 { get; set; }
        public Nullable<double> Score0_7 { get; set; }
        public Nullable<double> Score0_8 { get; set; }
        public Nullable<double> Score0_9 { get; set; }
        public Nullable<double> Score0_10 { get; set; }
        public Nullable<int> Score1_1 { get; set; }
        public Nullable<int> Score1_2 { get; set; }
        public Nullable<int> Score1_3 { get; set; }
        public Nullable<int> Score1_4 { get; set; }
        public Nullable<int> Score1_5 { get; set; }
        public Nullable<int> Score1_6 { get; set; }
        public Nullable<int> Score1_7 { get; set; }
        public Nullable<int> Score1_8 { get; set; }
        public Nullable<int> Score1_9 { get; set; }
        public Nullable<int> Score1_10 { get; set; }
        public Nullable<double> Score2_1 { get; set; }
        public Nullable<double> Score2_2 { get; set; }
        public Nullable<double> Score2_3 { get; set; }
        public Nullable<double> Score2_4 { get; set; }
        public Nullable<double> Score2_5 { get; set; }
        public Nullable<double> Score2_6 { get; set; }
        public Nullable<double> Score2_7 { get; set; }
        public Nullable<double> Score2_8 { get; set; }
        public Nullable<double> Score2_9 { get; set; }
        public Nullable<double> Score2_10 { get; set; }
        /// <summary>
        /// 赛事类型
        /// </summary>
        public string GameType0 { get; set; }
        public string GameType1 { get; set; }
        public string GameType2 { get; set; }
        public string GameType3 { get; set; }
        public string GameType4 { get; set; }
        public string GameType5 { get; set; }
        public string GameType6 { get; set; }
        public string GameType7 { get; set; }
        public string GameType8 { get; set; }
        public string GameType9 { get; set; }
        /// <summary>
        /// 过关注单编号
        /// </summary>
        public Nullable<decimal> BillParlay0 { get; set; }
        public Nullable<decimal> BillParlay1 { get; set; }
        public Nullable<decimal> BillParlay2 { get; set; }
        public Nullable<decimal> BillParlay3 { get; set; }
        public Nullable<decimal> BillParlay4 { get; set; }
        public Nullable<decimal> BillParlay5 { get; set; }
        public Nullable<decimal> BillParlay6 { get; set; }
        public Nullable<decimal> BillParlay7 { get; set; }
        public Nullable<decimal> BillParlay8 { get; set; }
        public Nullable<decimal> BillParlay9 { get; set; }
        /// <summary>
        /// 联盟
        /// </summary>
        public string Alliance0 { get; set; }
        public string Alliance1 { get; set; }
        public string Alliance2 { get; set; }
        public string Alliance3 { get; set; }
        public string Alliance4 { get; set; }
        public string Alliance5 { get; set; }
        public string Alliance6 { get; set; }
        public string Alliance7 { get; set; }
        public string Alliance8 { get; set; }
        public string Alliance9 { get; set; }

        public Nullable<int> ParentFlag { get; set; }

        public Nullable<System.DateTime> CloseAccountTime { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Demotion { get; set; }

        public new Nullable<int> f_demo { get; set; }
        public new string f_DCinfoID { get; set; }
    }
}
