using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlyingSnow.Contract.Bill
{
    public partial class OldParlayBill
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> f_date { get; set; }
        public Nullable<System.DateTime> f_time { get; set; }
        public Nullable<decimal> f_id { get; set; }
        public string f_typ1 { get; set; }
        public Nullable<double> f_money { get; set; }
        public Nullable<double> f_result { get; set; }
        public Nullable<double> f_ty { get; set; }
        public Nullable<double> f_mresult { get; set; }
        public string f_member { get; set; }
        public Nullable<double> f_yssy { get; set; }
        public Nullable<byte> f_js { get; set; }
        public Nullable<byte> f_peril { get; set; }
        public string f_majordomo { get; set; }
        public string f_bigpartner { get; set; }
        public string f_partner { get; set; }
        public string f_generalagent { get; set; }
        public string f_alagent { get; set; }
        public Nullable<double> f_mo1 { get; set; }
        public Nullable<double> f_mo2 { get; set; }
        public Nullable<double> f_mo3 { get; set; }
        public Nullable<double> f_mo4 { get; set; }
        public Nullable<byte> f_del { get; set; }
        public string f_content_1 { get; set; }
        public string f_content_2 { get; set; }
        public string f_content_3 { get; set; }
        public string f_content_4 { get; set; }
        public string f_content_5 { get; set; }
        public string f_content_6 { get; set; }
        public string f_content_7 { get; set; }
        public string f_content_8 { get; set; }
        public string f_content_9 { get; set; }
        public string f_content_10 { get; set; }
        public string f_team_1 { get; set; }
        public string f_team_2 { get; set; }
        public string f_team_3 { get; set; }
        public string f_team_4 { get; set; }
        public string f_team_5 { get; set; }
        public string f_team_6 { get; set; }
        public string f_team_7 { get; set; }
        public string f_team_8 { get; set; }
        public string f_team_9 { get; set; }
        public string f_team_10 { get; set; }
        public Nullable<double> f_pl_1 { get; set; }
        public Nullable<double> f_pl_2 { get; set; }
        public Nullable<double> f_pl_3 { get; set; }
        public Nullable<double> f_pl_4 { get; set; }
        public Nullable<double> f_pl_5 { get; set; }
        public Nullable<double> f_pl_6 { get; set; }
        public Nullable<double> f_pl_7 { get; set; }
        public Nullable<double> f_pl_8 { get; set; }
        public Nullable<double> f_pl_9 { get; set; }
        public Nullable<double> f_pl_10 { get; set; }
        public Nullable<double> f_rrf0_1 { get; set; }
        public Nullable<double> f_rrf0_2 { get; set; }
        public Nullable<double> f_rrf0_3 { get; set; }
        public Nullable<double> f_rrf0_4 { get; set; }
        public Nullable<double> f_rrf0_5 { get; set; }
        public Nullable<double> f_rrf0_6 { get; set; }
        public Nullable<double> f_rrf0_7 { get; set; }
        public Nullable<double> f_rrf0_8 { get; set; }
        public Nullable<double> f_rrf0_9 { get; set; }
        public Nullable<double> f_rrf0_10 { get; set; }
        public Nullable<int> f_rrf1_1 { get; set; }
        public Nullable<int> f_rrf1_2 { get; set; }
        public Nullable<int> f_rrf1_3 { get; set; }
        public Nullable<int> f_rrf1_4 { get; set; }
        public Nullable<int> f_rrf1_5 { get; set; }
        public Nullable<int> f_rrf1_6 { get; set; }
        public Nullable<int> f_rrf1_7 { get; set; }
        public Nullable<int> f_rrf1_8 { get; set; }
        public Nullable<int> f_rrf1_9 { get; set; }
        public Nullable<int> f_rrf1_10 { get; set; }
        public Nullable<double> f_rrf2_1 { get; set; }
        public Nullable<double> f_rrf2_2 { get; set; }
        public Nullable<double> f_rrf2_3 { get; set; }
        public Nullable<double> f_rrf2_4 { get; set; }
        public Nullable<double> f_rrf2_5 { get; set; }
        public Nullable<double> f_rrf2_6 { get; set; }
        public Nullable<double> f_rrf2_7 { get; set; }
        public Nullable<double> f_rrf2_8 { get; set; }
        public Nullable<double> f_rrf2_9 { get; set; }
        public Nullable<double> f_rrf2_10 { get; set; }
        public Nullable<int> f_rrf3_1 { get; set; }
        public Nullable<int> f_rrf3_2 { get; set; }
        public Nullable<int> f_rrf3_3 { get; set; }
        public Nullable<int> f_rrf3_4 { get; set; }
        public Nullable<int> f_rrf3_5 { get; set; }
        public Nullable<int> f_rrf3_6 { get; set; }
        public Nullable<int> f_rrf3_7 { get; set; }
        public Nullable<int> f_rrf3_8 { get; set; }
        public Nullable<int> f_rrf3_9 { get; set; }
        public Nullable<int> f_rrf3_10 { get; set; }
        public Nullable<double> f_ddx0_1 { get; set; }
        public Nullable<double> f_ddx0_2 { get; set; }
        public Nullable<double> f_ddx0_3 { get; set; }
        public Nullable<double> f_ddx0_4 { get; set; }
        public Nullable<double> f_ddx0_5 { get; set; }
        public Nullable<double> f_ddx0_6 { get; set; }
        public Nullable<double> f_ddx0_7 { get; set; }
        public Nullable<double> f_ddx0_8 { get; set; }
        public Nullable<double> f_ddx0_9 { get; set; }
        public Nullable<double> f_ddx0_10 { get; set; }
        public Nullable<int> f_ddx1_1 { get; set; }
        public Nullable<int> f_ddx1_2 { get; set; }
        public Nullable<int> f_ddx1_3 { get; set; }
        public Nullable<int> f_ddx1_4 { get; set; }
        public Nullable<int> f_ddx1_5 { get; set; }
        public Nullable<int> f_ddx1_6 { get; set; }
        public Nullable<int> f_ddx1_7 { get; set; }
        public Nullable<int> f_ddx1_8 { get; set; }
        public Nullable<int> f_ddx1_9 { get; set; }
        public Nullable<int> f_ddx1_10 { get; set; }
        public Nullable<double> f_ddx2_1 { get; set; }
        public Nullable<double> f_ddx2_2 { get; set; }
        public Nullable<double> f_ddx2_3 { get; set; }
        public Nullable<double> f_ddx2_4 { get; set; }
        public Nullable<double> f_ddx2_5 { get; set; }
        public Nullable<double> f_ddx2_6 { get; set; }
        public Nullable<double> f_ddx2_7 { get; set; }
        public Nullable<double> f_ddx2_8 { get; set; }
        public Nullable<double> f_ddx2_9 { get; set; }
        public Nullable<double> f_ddx2_10 { get; set; }
        public string f_type_1 { get; set; }
        public string f_type_2 { get; set; }
        public string f_type_3 { get; set; }
        public string f_type_4 { get; set; }
        public string f_type_5 { get; set; }
        public string f_type_6 { get; set; }
        public string f_type_7 { get; set; }
        public string f_type_8 { get; set; }
        public string f_type_9 { get; set; }
        public string f_type_10 { get; set; }
        public Nullable<decimal> f_id_1 { get; set; }
        public Nullable<decimal> f_id_2 { get; set; }
        public Nullable<decimal> f_id_3 { get; set; }
        public Nullable<decimal> f_id_4 { get; set; }
        public Nullable<decimal> f_id_5 { get; set; }
        public Nullable<decimal> f_id_6 { get; set; }
        public Nullable<decimal> f_id_7 { get; set; }
        public Nullable<decimal> f_id_8 { get; set; }
        public Nullable<decimal> f_id_9 { get; set; }
        public Nullable<decimal> f_id_10 { get; set; }
        public Nullable<double> f_ty0 { get; set; }
        public Nullable<double> f_ty01 { get; set; }
        public Nullable<double> f_ty02 { get; set; }
        public Nullable<double> f_ty03 { get; set; }
        public Nullable<double> f_ty04 { get; set; }
        public Nullable<double> f_ty00 { get; set; }
        public string f_con_1 { get; set; }
        public string f_con_2 { get; set; }
        public string f_con_3 { get; set; }
        public string f_con_4 { get; set; }
        public string f_con_5 { get; set; }
        public string f_con_6 { get; set; }
        public string f_con_7 { get; set; }
        public string f_con_8 { get; set; }
        public string f_con_9 { get; set; }
        public string f_con_10 { get; set; }
        public string f_ip { get; set; }
        public Nullable<double> f_mo { get; set; }
        public Nullable<double> f_mo0 { get; set; }
        public Nullable<double> f_mo5 { get; set; }
        public Nullable<int> f_demo { get; set; }
        public Nullable<double> f_cc0 { get; set; }
        public Nullable<double> f_cc1 { get; set; }
        public Nullable<double> f_cc2 { get; set; }
        public Nullable<double> f_cc3 { get; set; }
        public Nullable<double> f_cc4 { get; set; }
        public string f_AuthCode { get; set; }
        public string f_typ2 { get; set; }
        public string f_typ3 { get; set; }
        public string f_typ4 { get; set; }
        public string f_typ5 { get; set; }
        public string f_typ6 { get; set; }
        public string f_typ7 { get; set; }
        public string f_typ8 { get; set; }
        public string f_typ9 { get; set; }
        public string f_typ10 { get; set; }
        public Nullable<double> f_SurplusMoney { get; set; }
        public Nullable<System.DateTime> f_jstime { get; set; }
        public Nullable<byte> f_way { get; set; }
        public Nullable<byte> f_exflag { get; set; }
        public string f_area { get; set; }
        public string f_motherid { get; set; }
        public Nullable<byte> f_jscount { get; set; }
        public Nullable<byte> f_ischange { get; set; }
        public Nullable<int> f_jxstatus { get; set; }
        public string f_DCinfoID { get; set; }
    }
}
