using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlyingSnow.Contract.Base
{
    public partial class GameControl
    {
        public int Id { get; set; }
        public Nullable<int> Spread { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Single { get; set; }
        public Nullable<int> OneLoseTwoWin { get; set; }
        public Nullable<int> SingleOrDouble { get; set; }
        public Nullable<int> BallingSpread { get; set; }
        public Nullable<int> BallingScore { get; set; }
        public Nullable<int> BallingSignleOrDouble { get; set; }
        public Nullable<int> VieFirstPoint { get; set; }
        public Nullable<int> VieLastPoint { get; set; }
        public Nullable<int> f_z_djzgdf { get; set; }
        public Nullable<int> f_z_zkzdfrf { get; set; }
        public Nullable<int> f_z_zkzdfdx { get; set; }
        public Nullable<int> f_z_zkzdfdy { get; set; }
        public Nullable<int> f_z_zkzdfysey { get; set; }
        public Nullable<int> f_z_zkzdfds { get; set; }
        public Nullable<int> SumOddsScore { get; set; }
        public Nullable<int> Champion { get; set; }
        public Nullable<int> Parlay { get; set; }
        public Nullable<int> SpreadOfFirst { get; set; }
        public Nullable<int> ScoreOfFirst { get; set; }
        public Nullable<int> CapotOfFirst { get; set; }
        public Nullable<int> SingleOrDoubleOfFirst { get; set; }
        public Nullable<int> SpreadOfFirstHalf { get; set; }
        public Nullable<int> ScoreOfFirstHalf { get; set; }
        public Nullable<int> CapotOfFirstHalf { get; set; }
        public Nullable<int> SingleOrDoubleOfFirstHalf { get; set; }
        public Nullable<int> SpreadOfFirstHalfGo { get; set; }
        public Nullable<int> ScoreOfFirstHalfGo { get; set; }
        public Nullable<int> SingleOrDoubleOfFirstHalfGo { get; set; }
        public Nullable<int> SpreadOfSecondHalf { get; set; }
        public Nullable<int> ScoreOfSecondHalf { get; set; }
        public Nullable<int> CapotOfSecondHalf { get; set; }
        public Nullable<int> SingleOrDoubleOfSecondHalf { get; set; }
        public Nullable<int> SpreadOfSecondHalfGo { get; set; }
        public Nullable<int> ScoreOfSecondHalfGo { get; set; }
        public Nullable<int> SingleOrDoubleOfSecondHalfGo { get; set; }
        public Nullable<int> ReferPoint { get; set; }
        public Nullable<double> SpreadLimited { get; set; }
        public Nullable<double> ScoreLimited { get; set; }
        public Nullable<double> CapotLimited { get; set; }
        public Nullable<double> OneLoseTwoWinLimited { get; set; }
        public Nullable<double> SingleOrDoubleLimited { get; set; }
        public Nullable<double> SpreadGoLimited { get; set; }
        public Nullable<double> ScoreGoLimited { get; set; }
        public Nullable<double> CapotGoLimited { get; set; }
        public Nullable<double> VieFirstPointLimited { get; set; }
        public Nullable<double> f_x_qwf { get; set; }
        public Nullable<double> f_x_zkzdfrf { get; set; }
        public Nullable<double> f_x_zkzdfdx { get; set; }
        public Nullable<double> f_x_zkzdfdy { get; set; }
        public Nullable<double> f_x_zkzdfysey { get; set; }
        public Nullable<double> f_x_zkzdfds { get; set; }
        public Nullable<double> f_x_djzgrf { get; set; }
        public Nullable<double> f_x_gj { get; set; }
        public Nullable<double> f_x_gg { get; set; }
        public Nullable<double> f_x_dyjrf { get; set; }
        public Nullable<double> f_x_dyjdx { get; set; }
        public Nullable<double> f_x_dyjdy { get; set; }
        public Nullable<double> f_x_dyjds { get; set; }
        public Nullable<double> f_x_sbcrf { get; set; }
        public Nullable<double> f_x_sbcdx { get; set; }
        public Nullable<double> f_x_sbcdy { get; set; }
        public Nullable<double> f_x_sbcds { get; set; }
        public Nullable<double> f_x_sbczdrf { get; set; }
        public Nullable<double> f_x_sbczddx { get; set; }
        public Nullable<double> f_x_sbczdds { get; set; }
        public Nullable<double> f_x_xbcrf { get; set; }
        public Nullable<double> f_x_xbcdx { get; set; }
        public Nullable<double> f_x_xbcdy { get; set; }
        public Nullable<double> f_x_xbcds { get; set; }
        public Nullable<double> f_x_xbczdrf { get; set; }
        public Nullable<double> f_x_xbczddx { get; set; }
        public Nullable<double> f_x_xbczdds { get; set; }
        public Nullable<double> f_x_jzf { get; set; }
        public Nullable<double> f_d_rf { get; set; }
        public Nullable<double> f_d_dx { get; set; }
        public Nullable<double> f_d_dy { get; set; }
        public Nullable<double> f_d_ysey { get; set; }
        public Nullable<double> f_d_ds { get; set; }
        public Nullable<double> f_d_zdrf { get; set; }
        public Nullable<double> f_d_zddx { get; set; }
        public Nullable<double> f_d_zdds { get; set; }
        public Nullable<double> f_d_qsf { get; set; }
        public Nullable<double> f_d_qwf { get; set; }
        public Nullable<double> f_d_zkzdfrf { get; set; }
        public Nullable<double> f_d_zkzdfdx { get; set; }
        public Nullable<double> f_d_zkzdfdy { get; set; }
        public Nullable<double> f_d_zkzdfysey { get; set; }
        public Nullable<double> f_d_zkzdfds { get; set; }
        public Nullable<double> f_d_djzgrf { get; set; }
        public Nullable<double> f_d_gj { get; set; }
        public Nullable<double> f_d_gg { get; set; }
        public Nullable<double> f_d_dyjrf { get; set; }
        public Nullable<double> f_d_dyjdx { get; set; }
        public Nullable<double> f_d_dyjdy { get; set; }
        public Nullable<double> f_d_dyjds { get; set; }
        public Nullable<double> f_d_sbcrf { get; set; }
        public Nullable<double> f_d_sbcdx { get; set; }
        public Nullable<double> f_d_sbcdy { get; set; }
        public Nullable<double> f_d_sbcds { get; set; }
        public Nullable<double> f_d_sbczdrf { get; set; }
        public Nullable<double> f_d_sbczddx { get; set; }
        public Nullable<double> f_d_sbczdds { get; set; }
        public Nullable<double> f_d_xbcrf { get; set; }
        public Nullable<double> f_d_xbcdx { get; set; }
        public Nullable<double> f_d_xbcdy { get; set; }
        public Nullable<double> f_d_xbcds { get; set; }
        public Nullable<double> f_d_xbczdrf { get; set; }
        public Nullable<double> f_d_xbczddx { get; set; }
        public Nullable<double> f_d_xbczdds { get; set; }
        public Nullable<double> f_d_jzf { get; set; }
        public Nullable<double> f_j_rf { get; set; }
        public Nullable<double> f_j_dx { get; set; }
        public Nullable<double> f_j_dy { get; set; }
        public Nullable<double> f_j_ysey { get; set; }
        public Nullable<double> f_j_ds { get; set; }
        public Nullable<double> f_j_zdrf { get; set; }
        public Nullable<double> f_j_zddx { get; set; }
        public Nullable<double> f_j_zdds { get; set; }
        public Nullable<double> f_j_qsf { get; set; }
        public Nullable<double> f_j_qwf { get; set; }
        public Nullable<double> f_j_zkzdfrf { get; set; }
        public Nullable<double> f_j_zkzdfdx { get; set; }
        public Nullable<double> f_j_zkzdfdy { get; set; }
        public Nullable<double> f_j_zkzdfysey { get; set; }
        public Nullable<double> f_j_zkzdfds { get; set; }
        public Nullable<double> f_j_djzgrf { get; set; }
        public Nullable<double> f_j_gj { get; set; }
        public Nullable<double> f_j_gg { get; set; }
        public Nullable<double> f_j_dyjrf { get; set; }
        public Nullable<double> f_j_dyjdx { get; set; }
        public Nullable<double> f_j_dyjdy { get; set; }
        public Nullable<double> f_j_dyjds { get; set; }
        public Nullable<double> f_j_sbcrf { get; set; }
        public Nullable<double> f_j_sbcdx { get; set; }
        public Nullable<double> f_j_sbcdy { get; set; }
        public Nullable<double> f_j_sbcds { get; set; }
        public Nullable<double> f_j_sbczdrf { get; set; }
        public Nullable<double> f_j_sbczddx { get; set; }
        public Nullable<double> f_j_sbczdds { get; set; }
        public Nullable<double> f_j_xbcrf { get; set; }
        public Nullable<double> f_j_xbcdx { get; set; }
        public Nullable<double> f_j_xbcdy { get; set; }
        public Nullable<double> f_j_xbcds { get; set; }
        public Nullable<double> f_j_xbczdrf { get; set; }
        public Nullable<double> f_j_xbczddx { get; set; }
        public Nullable<double> f_j_xbczdds { get; set; }
        public Nullable<double> f_j_jzf { get; set; }
        public Nullable<double> f_p_rf { get; set; }
        public Nullable<double> f_p_dx { get; set; }
        public Nullable<double> f_p_dy { get; set; }
        public Nullable<double> f_p_ysey { get; set; }
        public Nullable<double> f_p_ds { get; set; }
        public Nullable<double> f_p_zdrf { get; set; }
        public Nullable<double> f_p_zddx { get; set; }
        public Nullable<double> f_p_zdds { get; set; }
        public Nullable<double> f_p_qsf { get; set; }
        public Nullable<double> f_p_qwf { get; set; }
        public Nullable<double> f_p_zkzdfrf { get; set; }
        public Nullable<double> f_p_zkzdfdx { get; set; }
        public Nullable<double> f_p_zkzdfdy { get; set; }
        public Nullable<double> f_p_zkzdfysey { get; set; }
        public Nullable<double> f_p_zkzdfds { get; set; }
        public Nullable<double> f_p_djzgrf { get; set; }
        public Nullable<double> f_p_gj { get; set; }
        public Nullable<double> f_p_gg { get; set; }
        public Nullable<double> f_p_dyjrf { get; set; }
        public Nullable<double> f_p_dyjdx { get; set; }
        public Nullable<double> f_p_dyjdy { get; set; }
        public Nullable<double> f_p_dyjds { get; set; }
        public Nullable<double> f_p_sbcrf { get; set; }
        public Nullable<double> f_p_sbcdx { get; set; }
        public Nullable<double> f_p_sbcdy { get; set; }
        public Nullable<double> f_p_sbcds { get; set; }
        public Nullable<double> f_p_sbczdrf { get; set; }
        public Nullable<double> f_p_sbczddx { get; set; }
        public Nullable<double> f_p_sbczdds { get; set; }
        public Nullable<double> f_p_xbcrf { get; set; }
        public Nullable<double> f_p_xbcdx { get; set; }
        public Nullable<double> f_p_xbcdy { get; set; }
        public Nullable<double> f_p_xbcds { get; set; }
        public Nullable<double> f_p_xbczdrf { get; set; }
        public Nullable<double> f_p_xbczddx { get; set; }
        public Nullable<double> f_p_xbczdds { get; set; }
        public Nullable<double> f_p_jzf { get; set; }
        public Nullable<int> f_sfkfbskg { get; set; }
        public Nullable<int> f_ldfz { get; set; }
    }
}
