//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyingSnow.Database
{
    using Contract.Bill;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BillDBContext : DbContext
    {
        public BillDBContext()
            : base("name=BillEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<ParlayBill> ParlayBills { get; set; }
    }
}
