//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyingSnow.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_a_preserve
    {
        public int f_id { get; set; }
        public Nullable<int> f_live { get; set; }
        public string f_graphic { get; set; }
        public Nullable<bool> f_isOpen { get; set; }
    }
}
