//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyingSnow.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_member
    {
        public decimal id { get; set; }
        public string f_accounts { get; set; }
        public string f_password { get; set; }
        public string f_title { get; set; }
        public Nullable<double> f_residualcredit { get; set; }
        public Nullable<int> f_peril { get; set; }
        public Nullable<int> f_enter { get; set; }
        public Nullable<int> f_spit { get; set; }
        public Nullable<System.DateTime> f_enterdate { get; set; }
        public Nullable<System.DateTime> f_spitdate { get; set; }
        public Nullable<int> f_defer { get; set; }
        public Nullable<double> f_lower { get; set; }
        public string f_remark { get; set; }
        public string f_majordomo { get; set; }
        public string f_bigpartner { get; set; }
        public string f_partner { get; set; }
        public string f_generalagent { get; set; }
        public string f_alagent { get; set; }
        public Nullable<int> f_lq { get; set; }
        public Nullable<int> f_bj { get; set; }
        public Nullable<int> f_by { get; set; }
        public Nullable<int> f_zq { get; set; }
        public Nullable<int> f_mz { get; set; }
        public Nullable<int> f_error { get; set; }
        public Nullable<System.DateTime> f_time { get; set; }
        public string f_ip { get; set; }
        public Nullable<int> f_bb { get; set; }
        public Nullable<System.DateTime> f_joindate { get; set; }
        public Nullable<int> f_zs { get; set; }
        public Nullable<System.DateTime> f_xgtime { get; set; }
        public Nullable<int> f_Tollgate { get; set; }
        public string f_modifier { get; set; }
        public Nullable<int> f_sm { get; set; }
        public string f_UserHead { get; set; }
        public Nullable<int> f_UserGender { get; set; }
        public Nullable<double> f_game { get; set; }
        public Nullable<int> f_passwordjy { get; set; }
        public Nullable<int> f_wq { get; set; }
        public Nullable<int> f_bq { get; set; }
        public Nullable<int> f_hb { get; set; }
        public Nullable<int> f_cq { get; set; }
        public Nullable<int> f_ss { get; set; }
        public Nullable<int> f_StupeSurplus { get; set; }
        public string f_VoicePass { get; set; }
        public string f_RemittanceAccount { get; set; }
        public string f_RemittanceName { get; set; }
        public string f_SecurityProblem { get; set; }
        public string f_SecurityAnswer { get; set; }
        public string f_BankCode { get; set; }
        public Nullable<int> f_Vd { get; set; }
        public Nullable<int> f_Et { get; set; }
        public Nullable<int> f_VDStupeSurplus { get; set; }
        public Nullable<double> f_bonus { get; set; }
        public Nullable<int> f_ot { get; set; }
        public string f_NowGame { get; set; }
        public Nullable<int> f_FHCredit { get; set; }
        public Nullable<int> f_passwordjy2 { get; set; }
        public string f_SubBank { get; set; }
        public int f_periltypes { get; set; }
        public Nullable<double> f_vdzssx { get; set; }
        public string f_RemarkText { get; set; }
        public Nullable<byte> f_zh { get; set; }
        public Nullable<byte> f_pdpass { get; set; }
        public string epayInAccount { get; set; }
        public string epayOutAccount { get; set; }
        public string epayName { get; set; }
        public string etpInAccount { get; set; }
        public string etpOutAccount { get; set; }
        public string etpName { get; set; }
        public Nullable<int> f_creditchagetype { get; set; }
        public Nullable<byte> f_Record { get; set; }
        public Nullable<byte> f_autoWhite { get; set; }
        public Nullable<decimal> f_ballid { get; set; }
        public string f_type { get; set; }
        public Nullable<System.DateTime> f_intime { get; set; }
        public Nullable<int> f_mode { get; set; }
        public Nullable<byte> f_pk { get; set; }
        public Nullable<double> f_AGSurplus2 { get; set; }
        public Nullable<double> f_MGSurplus2 { get; set; }
        public string f_SB_token { get; set; }
        public Nullable<double> f_CNFSurplus2 { get; set; }
        public Nullable<double> f_SBSurplus2 { get; set; }
        public Nullable<double> f_DJSurplus2 { get; set; }
        public Nullable<byte> f_unhmd { get; set; }
        public Nullable<int> f_gamemode { get; set; }
        public Nullable<double> f_OGSurplus2 { get; set; }
        public Nullable<double> f_BBINSurplus2 { get; set; }
        public Nullable<double> f_ChatroomSurplus2 { get; set; }
        public Nullable<double> f_ABSurplus2 { get; set; }
        public Nullable<double> f_AGIframeSurplus2 { get; set; }
        public Nullable<double> f_AGIPlatfromSurplus { get; set; }
        public Nullable<double> f_HBSurplus2 { get; set; }
        public Nullable<double> f_VdSurplus2 { get; set; }
        public Nullable<double> f_SUNSurplus2 { get; set; }
        public string f_CMD_token { get; set; }
        public Nullable<double> f_CMDSurplus2 { get; set; }
        public Nullable<double> f_SCSurplus2 { get; set; }
        public string f_remark3 { get; set; }
    }
}
