//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyingSnow.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_system
    {
        public string f_mode { get; set; }
        public Nullable<System.DateTime> f_datae { get; set; }
        public Nullable<System.DateTime> f_datae2 { get; set; }
        public Nullable<int> f_ipday { get; set; }
        public Nullable<double> f_change { get; set; }
        public Nullable<int> f_memberenter { get; set; }
        public Nullable<double> f_credit { get; set; }
        public Nullable<double> f_peril { get; set; }
        public Nullable<int> f_xdefer { get; set; }
        public string f_zdefer { get; set; }
        public Nullable<double> f_bbec { get; set; }
        public Nullable<double> f_abec { get; set; }
        public Nullable<int> f_notenter { get; set; }
        public string f_ip { get; set; }
        public Nullable<double> f_gcsx { get; set; }
        public Nullable<int> f_qx { get; set; }
        public Nullable<int> f_cz { get; set; }
        public Nullable<double> f_hyxx { get; set; }
        public Nullable<int> f_flash { get; set; }
        public Nullable<System.DateTime> f_finallytime { get; set; }
        public Nullable<double> f_xzjedy { get; set; }
        public Nullable<int> f_closecolor { get; set; }
        public string f_js_set { get; set; }
        public Nullable<int> f_x { get; set; }
        public Nullable<int> f_y { get; set; }
        public Nullable<int> f_z { get; set; }
        public byte f_ipsecond { get; set; }
        public byte f_gipsecond { get; set; }
        public Nullable<byte> f_gzing { get; set; }
        public Nullable<byte> f_xqkf { get; set; }
        public Nullable<int> f_entercountry { get; set; }
        public Nullable<double> f_ballpk_A { get; set; }
        public Nullable<double> f_ballpk_B { get; set; }
        public Nullable<int> f_looknode { get; set; }
        public Nullable<int> f_fzStatus { get; set; }
        public Nullable<byte> f_leavehours { get; set; }
        public Nullable<byte> f_mobilekf { get; set; }
        public string f_majordomo { get; set; }
        public Nullable<byte> f_Iszdjs { get; set; }
        public Nullable<byte> f_fgspMode { get; set; }
        public string f_majordomo_set { get; set; }
        public Nullable<double> f_ggxx { get; set; }
        public Nullable<double> f_initialcredit { get; set; }
        public string f_testmajordomo { get; set; }
    }
}
